name: Build (Linux & Windows, Static & Dynamic)

on:
  push:
    branches: [ actions-testing ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y
          libgl1-mesa-dev
          libx11-dev
          libxrandr-dev
          libxinerama-dev
          libxcursor-dev
          libxi-dev

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Bootstrap vcpkg
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: Configure CMake
        run: >
          cmake -B build-linux
          -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=x64-linux
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build-linux --config Release

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: build-linux/*

  build-windows-static:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        run: |
          # Bootstrap vcpkg (Windows)
          .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
          echo "VCPKG_ROOT=$env:GITHUB_WORKSPACE\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Configure CMake
        run: >
          cmake -B build-static 
          -DCMAKE_TOOLCHAIN_FILE=".\vcpkg\scripts\buildsystems\vcpkg.cmake"
          -DVCPKG_TARGET_TRIPLET=x64-windows-static
          -DCMAKE_BUILD_TYPE=Release

      - name: Build (static)
        run: cmake --build build-static --config Release

      - name: Upload Windows Static Binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-static-binary
          path: build-static/*.exe

  build-windows-dynamic:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        run: |
          # Bootstrap vcpkg (Windows)
          .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
          echo "VCPKG_ROOT=${{ github.workspace }}\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Configure CMake
        run: >
          cmake -B build-dynamic
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"
          -DVCPKG_TARGET_TRIPLET=x64-windows
          -DCMAKE_BUILD_TYPE=Release

      - name: Build (Dynamic)
        run: cmake --build build-dynamic --config Release

      - name: Upload Windows Dynamic Binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-dynamic-binary
          path: build-dynamic/*.exe
