name: Build (Linux & Windows, Static & Dynamic)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Bootstrap vcpkg
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: Configure CMake
        run: cmake -B build-linux -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build-linux --config Release

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: build-linux/*

  build-windows-static:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Configure CMake (Static)
        run: cmake -B build-static -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release

      - name: Build (Static)
        run: cmake --build build-static --config Release

      - name: Upload Windows Static Binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-static-binary
          path: build-static/*.exe

  build-windows-dynamic:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Configure CMake (Dynamic)
        run: cmake -B build-dynamic -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_BUILD_TYPE=Release

      - name: Build (Dynamic)
        run: cmake --build build-dynamic --config Release

      - name: Upload Windows Dynamic Binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-dynamic-binary
          path: build-dynamic/*.exe
